language: node_js
node_js:
 - 10.16.3

cache: npm

services:
  - postgresql

before_install:
  - npm install -g npm@latest
  - npm i -g @adonisjs/cli

install: 
  - npm ci

env:
  - DB_URL = postgres://jmjkecsrkmejwd:37672200b9680714bff3b4978e1cb990975841ea22b91ce82180b1cd28b9a270@ec2-107-22-224-154.compute-1.amazonaws.com:5432/d1p7db7vh98cgv

before_script:
  - psql -c 'CREATE DATABASE listactividades;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres

script: 
  - adonis migration:run
  - adonis test

provider: heroku
api_key:
  secure: a908fc05-83b5-48dd-ab64-96cbe5eaf14a