language: node_js
node_js:
 - 10.16.3

cache: npm

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE listactividades;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

script: 
  -npm i -g @adonisjs/cli
  -npm install
  -adonis test

provider: heroku
api_key:
  secure: a908fc05-83b5-48dd-ab64-96cbe5eaf14a