language: node_js
node_js:
 - 10.16.3

sudo: false

cache:
  directories:
  - node_modules

services:
  - postgresql

before_install:
  - npm install -g npm@latest
  - npm i -g @adonisjs/cli

install: 
  - npm ci

script: 
  - adonis migration:run
  - adonis test

provider: heroku
api_key:
  secure: a908fc05-83b5-48dd-ab64-96cbe5eaf14a