language: node_js
node_js:
 - 10.16.3

cache: npm

services:
  - postgresql

before_install:
  - npm install -g npm@latest
  - npm i -g @adonisjs/cli

install: 
  - npm ci

before_script:
  - cp .env.testing .env
  - psql -c 'CREATE DATABASE listactividades;' -U postgres
  - adonis migration:run

script: 
  -adonis test

provider: heroku
api_key:
  secure: a908fc05-83b5-48dd-ab64-96cbe5eaf14a